apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::245103157297:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::245103157297:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-B74FCKCJ2MKM
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-05-02T18:39:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1479"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: dbfc1398-03a9-44ac-bc1d-d6c2e4591ec0
